### ISSUE TITLE
The service is down

### ISSUE THREAD

**Issue by Thesharing** [sntiagoma/zealusercontributions#1]
Thank you for providing such an excellent service for Zeal users to download user contribution docs.

But the service seems to have some issue on Heroku.

Could you please check what happened?

**Comment by xantiagoma** [comment]
Hi @Thesharing ,
According Heroku Panel app has execed the free hours for August.
We'd have to wait for September if runs again.

In the meanwhile I upload a mirror version of code to https://zealusercontributions.now.sh/

I was able to set heroku's maintenance page to show mirror (urls might not work but current home is enabled)

**Comment by Thesharing** [comment]
Thank you for being so kind!
